Plane-walker/Okeanos

proto/DCI/dci.proto

Add some kinds of message and rpc about router in dci.proto.

Update rpc of router in dci.proto.

---

proto/DCI/cccp.proto

New File. Ref #13

---

dock/cccp/test_cccp2.py

Test merge. Ref #19

---

dock/gnn/default_config.yaml
dock/gnn/graphSAGE.py
dock/gnn/node_classification.py
dock/gnn/random_walker.py
dock/gnn/sequence.py
dock/util/util.py

Create Node classification function
close #35

Create Node classification function

---

dock/netopter/graph_data.py
dock/netopter/node_classification.py

Create node embeding predict function.
close #37

Create node embeding predict function

---

protos/bci/bci.proto

interface about bci.
close #44

interface about bci. Ref #44

---

README.md
protos/dci/dci.proto

Add Node message and update Chain message in dci.proto.
Update README.md
close #24

Update dci.proto. Ref #24

---

.gitignore
README.md
dock/netopter/default_config.yaml
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py
dock/netopter/query_info.py
test/dock/netopter/test_node_classification.py

Add rpc call from BCI to get neighbor's info.
close #31

Add rpc call from BCI to get neighbor's info

---

protos/bci/bci.proto

Add the ReturnNextRouteId.
close #51

Add the NextRoute. Ref #51

---

protos/bci/bci.proto

Add the interface about callback, and modify the NextRC.
close #56

Add the interface about callback. Ref #56

---

dock/interface/dci_pb2.py
dock/interface/dci_pb2_grpc.py
protos/dci/dci.proto

Define Tx and packagedTx in proto. Renew  dci_pb2.py & dci_pb2_grpc.py file .Please review the two files for errors.
close #47

Define Tx and packagedTx in proto. Ref#47

---

.gitignore
dock/router/router.py
test/dock/router/test_router.py

Expose `next_node` function in router class in `router.py` file and add test file.
close #49

Expose next_node in router part. Ref #49

---

dock/netopter/network_optimizer.py
protos/dci/dci.proto

Node representation learning.
close #29
close #6

Node representation learning

---

README.md
dock/__init__.py
dock/default_config.yaml
dock/dock.py
dock/router/__init__.py
main.py
test/dock/router/test_router.py

Fix test router bug.
close #69

Fix test router bug

---

dock/dock.py
dock/router/default_router_config.yaml
dock/router/router.py

Add data_chain and add config for Router.
close #71

Add data_chain and add config for Router

---

dock/dock.py
dock/router/router.py
test/dock/router/test_router.py

* Fix the bug of test_next_node.
* Add test cases of info, transmit, callback.
close #76

Update test case for router

---

dock/netopter/network_optimizer.py
interface/dci/dci_pb2.py
protos/bci/bci.proto
protos/dci/dci.proto
test/dock/netopter/test_network_optimizer.py

Community info query.
close #8 
close #9

Community info query

---

.gitignore
dock/config/default_config.yaml
dock/default_config.yaml
dock/dock.py
dock/netopter/default_config.yaml
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py
dock/router/default_router_config.yaml
dock/router/router.py
main.py
protos/dci/dci.proto

Finish config folder create.
close #7 
close #83

Finish config folder create

---

dock/dock.py
dock/router/router.py
test/dock/router/test_router.py

Gossip periodically

---

dock/router/router.py
test/dock/router/test_router.py

Fix Chain type error in route bug. 
close #87

Fix Chain type error in route bug

---

dock/netopter/graph_data.py
dock/netopter/network_optimizer.py

Node choose a community.
close #30

Node choose a community

---

README.md
dock/cccp/cccp.py
dock/dock.py
interface/bci/bci_pb2.py
interface/bci/bci_pb2_grpc.py
protos/bci/bci.proto
test/dock/cccp/test_cccp.py

Deliver Tx to next chain. 
close #15 
close #48 
close #50

Deliver Tx to next chain. Ref #15 #48 #50

---

dock/router/router.py

Convert grpc to jsonrpc call.
close #101

Convert grpc to jsonrpc call

---

test/dock/router/test_router.py

Fix router test bug

---

island/service/base/server.py
island/service/base/utils.py
lane/service/base/server.py
lane/service/base/utils.py
log/log.py
main.py

Fix log for multiprocessing

---

dock/cccp/cccp.py
dock/netopter/graph_data.py
dock/router/router.py

Change grpc of bci into jsonrpc
close #97

Change grpc of bci into jsonrpc 

---

dock/manager/manager.py

Create island chain.
close #107

Create island chain

---

dock/cccp/cccp.py
dock/dock.py
dock/router/router.py
interface/sci/types/types_pb2.py
island/service/counter.py

Recognize target_id of tx then call dci. 
close #98

Recognize target_id of tx then call dci. Ref #98

---

dock/config/default_config.yaml
dock/dock.py
dock/manager/manager.py

Chain manager create chain.
close #34

Chain manager create chain

---

dock/dock.py
dock/manager/manager.py
dock/netopter/network_optimizer.py

Add log info for manager.
close #114

Add log info for manager

---

dock/manager/manager.py

leave_chain

---

dock/manager/manager.py
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py

Fix lane chain create number bug.
close #117

Fix lane chain create number bug

---

dock/config/default_config.yaml
dock/manager/manager.py

Node join in a chain in `manager.py`.
close #32

Node join in a chain

---

dock/cccp/cccp.py
interface/dci/dci_pb2.py
island/service/counter.py
lane/service/counter.py
protos/dci/dci.proto

Change counter for deliverTx/transmit/callback. 
close #112 
close #99

Change counter for deliverTx/transmit/callback. Ref #112

---

dock/manager/manager.py
island/service/__init__.py
island/service/service.py
lane/service/__init__.py
lane/service/service.py

Start and stop service
close #110 
close #111

Start and stop service

---

dock/manager/manager.py

Fix sed bug

---

island/service/service.py

Fix service not working properly.
close #131

Fix service not working properly

---

dock/dock.py
island/service/service.py

Fix level put error.
close #133

Fix level put error

---

island/service/service.py

Fix level get error.
close #135

Fix level get error

---

dock/router/router.py
island/service/service.py

Fix level utf-8 error.
close #137

Fix level utf-8 error

---

dock/manager/manager.py

Fix process wrong bug.
close #139

Fix process wrong bug

---

dock/cccp/cccp.py
dock/config/default_config.yaml
dock/dock.py
dock/manager/manager.py
dock/router/router.py
interface/dci/dci_pb2.py
interface/dci/dci_pb2_grpc.py
island/service/interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2_grpc.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
lane/service/interface/dci/dci_pb2_grpc.py
lane/service/service.py
protos/dci/dci.proto

Refactor cccp and router.
close #143

Refactor cccp and router

---

dock/manager/manager.py
island/service/service.py
lane/service/service.py

Fix manager service bug.
close #145

Fix manager service bug

---

dock/dock.py
island/service/service.py
lane/service/service.py

Service id_grpc chain bug.
close #147

Service id_grpc chain bug

---

dock/manager/manager.py

Add chain_id

---

island/service/service.py
lane/service/service.py

Update validator in a live network.
close #155

Update validator in a live network

---

dock/manager/manager.py
island/service/service.py
lane/service/service.py

Fix rpc call not work form remote node.
close #158

Fix rpc call not work form remote node

---

dock/config/default_config.yaml
dock/dock.py
dock/manager/manager.py

Join a live chain to start node.
close #160

Join a live chain to start node

---

dock/cccp/cccp.py
dock/dock.py
dock/manager/manager.py
environment.yml
island/service/service.py
lane/service/service.py
main.py
test/dock/cccp/config/dock.yaml
test/dock/cccp/test_cccp.py
test/dock/netopter/test_network_optimizer.py
test/dock/netopter/test_node_classification.py
test/dock/router/test_router.py

Hidden chains inside chain_manager and add try except in service.
close #164
close #127

Hidden chains inside chain_manager and add try except in service

---

island/service/service.py
lane/service/service.py
test/dock/cccp/test_cccp.py

Add more test for cccp.
close #166

Add more test for cccp

---

island/service/service.py
lane/service/service.py

info exception not show.
close #168

info exception not show

---

dock/manager/manager.py
main.py

Fix Dock config path error.
close #170

Fix Dock config path error

---

dock/manager/manager.py
island/service/service.py
lane/service/service.py
test/dock/cccp/test_cccp.py
test/dock/router/test_router.py

Timeout for chain start and manager update.
close #176

Timeout for chain start and manager update

---

dock/netopter/graph_data.py
interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
protos/dci/dci.proto
test/dock/netopter/test_graph_data.py

Update the form of graph data.
close #182

Update the form of graph data

---

dock/config/default_config.yaml
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py
test/dock/cccp/config/dock.yaml
test/dock/netopter/config/dock.yaml
test/dock/router/config/dock.yaml

Update node classification.
close #184

Update node classification

---

README.md

Update message format.
close #186

Update message format

---

island/service/service.py
test/dock/cccp/test_cccp.py
test/dock/netopter/test_graph_data.py

Update island service for header check.
close #188

Update island service for header check

---

README.md
dock/cccp/cccp.py
dock/cccp/message.py
dock/config/default_config.yaml
dock/dock.py
dock/router/package.py
dock/router/router.py
interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
lane/service/service.py
protos/dci/dci.proto
test/dock/router/test_router.py

Fix bugs of route

---

README.md
dock/cccp/cccp.py
dock/router/package.py
dock/router/router.py
lane/service/service.py
test/dock/router/test_router.py

Add index to use `ttl` correctly.
close #194

Add index to the message

---

dock/cccp/cccp.py
dock/manager/manager.py
island/service/service.py

Fix log error bug

---

dock/cccp/cccp.py
dock/router/router.py
test/dock/router/test_router.py

fix the deliver bug

---

dock/cccp/cccp.py
dock/dock.py
interface/dci/dci_pb2.py
interface/dci/dci_pb2_grpc.py
island/service/interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2_grpc.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
lane/service/interface/dci/dci_pb2_grpc.py
lane/service/service.py
protos/dci/dci.proto
test/dock/router/test_router.py

Cross query

---

README.md
dock/cccp/cccp.py
dock/dock.py
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py
island/service/service.py
test/dock/router/test_router.py

Get graph data from neighbor.
close #203

Get graph data from neighbor

---

dock/cccp/cccp.py

Check the duplicate message in cccp

---

dock/config/default_config.yaml
dock/manager/manager.py
dock/netopter/graph_data.py
test/dock/cccp/config/dock.yaml
test/dock/netopter/config/dock.yaml
test/dock/router/config/dock.yaml
test/dock/router/config/dock1.yaml
test/dock/router/test_router.py

Query genesis and id before join and send validate request after join.
close #207

Query genesis and id before join and send validate request after join

---

dock/cccp/cccp.py
dock/router/package.py
dock/router/router.py
island/service/log/log.py
lane/service/log/log.py
log/log.py

Enhance route process

---

dock/manager/manager.py

Set cache size to zero.
close #211

Set cache size to zero

---

README.md
dock/cccp/cccp.py
dock/router/package.py
dock/router/router.py

Fix route buf

---

README.md
dock/cccp/cccp.py
dock/manager/manager.py

Replay protection

---

README.md
dock/cccp/cccp.py
dock/dock.py
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
island/service/service.py
lane/service/service.py
test/dock/cccp/test_cccp.py
test/dock/netopter/test_graph_data.py
test/dock/router/test_router.py

Update switch island.
close #221

Update switch island

---

dock/manager/manager.py

Large client number.
close #223

Large client number

---

dock/cccp/cccp.py
island/service/service.py
lane/service/service.py

Add try for query

---

dock/cccp/cccp.py
dock/dock.py
dock/router/router.py

Clear paths when sending to island

---

dock/cccp/cccp.py
dock/dock.py
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
island/service/service.py
test/dock/cccp/test_cccp.py
test/dock/netopter/config/dock1.yaml
test/dock/netopter/test_graph_data.py
test/dock/netopter/test_node_classification.py
test/dock/router/test_router.py

Updata test for node classification.
close #229

Updata test for node classification

---

dock/router/package.py
dock/router/router.py

Fix missing app_id and timestamp

---

dock/config/default_config.yaml
dock/netopter/node_classification.py
test/dock/cccp/config/dock.yaml
test/dock/netopter/config/dock.yaml
test/dock/netopter/config/dock1.yaml
test/dock/router/config/dock.yaml
test/dock/router/config/dock1.yaml

Update prediction function.
close #233

Update prediction function

---

README.md
dock/cccp/cccp.py
dock/config/default_config.yaml
dock/manager/manager.py
dock/netopter/network_optimizer.py
interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
protos/dci/dci.proto
test/dock/cccp/config/dock.yaml
test/dock/netopter/config/dock.yaml
test/dock/netopter/config/dock1.yaml
test/dock/netopter/test_graph_data.py
test/dock/netopter/test_node_classification.py
test/dock/router/config/dock.yaml
test/dock/router/config/dock1.yaml
test/dock/router/test_router.py

Fix switch island not work bug.
close #235

Fix switch island not work bug

---

dock/cccp/cccp.py
dock/manager/manager.py
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
island/service/service.py
test/dock/cccp/test_cccp.py
test/dock/netopter/test_graph_data.py
test/dock/netopter/test_node_classification.py
test/dock/router/test_router.py

Remove the validator when delete a chain.
close #237

Remove the validator when delete a chain

---

dock/manager/manager.py
island/service/service.py
lane/service/service.py
test/dock/netopter/test_node_classification.py

Add empty type

---

dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
island/service/service.py
test/dock/netopter/test_graph_data.py
test/dock/router/test_router.py

Fix Multi node cross_query went wrong.
close #241

Fix Multi node cross_query went wrong

---

dock/cccp/cccp.py

Fix cross read timeout error bug.
close #243

Fix cross read timeout error bug

---

dock/cccp/cccp.py
island/service/service.py

Cross read not return app info.
close #245

Cross read not return app info

---

dock/netopter/network_optimizer.py
dock/netopter/node_classification.py

Stop switch if no new chain selected.
close #247

Stop switch if no new chain selected

---

dock/netopter/network_optimizer.py
dock/router/package.py
dock/router/router.py

Move router table into the island

---

dock/router/router.py
island/service/service.py

Add wrtie simple and read simlpe to island.
close #251

Add wrtie simple and read simlpe to island

---

dock/config/default_config.yaml
dock/manager/manager.py
dock/router/router.py
island/service/log/log.py
island/service/service.py
lane/service/log/log.py
lane/service/service.py
log/log.py
main.py
test/dock/cccp/config/dock.yaml
test/dock/netopter/config/dock.yaml
test/dock/netopter/config/dock1.yaml
test/dock/router/config/dock.yaml
test/dock/router/config/dock1.yaml

Change log location

---

dock/cccp/cccp.py
dock/dock.py
dock/manager/manager.py
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py
dock/router/package.py
dock/router/router.py
environment.yml
interface/dci/dci_pb2.py
interface/dci/dci_pb2_grpc.py
island/service/interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2_grpc.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
lane/service/interface/dci/dci_pb2_grpc.py
lane/service/service.py
main.py
protos/dci/dci.proto
test/dock/cccp/test_cccp.py
test/dock/netopter/test_graph_data.py
test/dock/netopter/test_node_classification.py
test/dock/router/test_router.py

Update atom cross move.
close #257

Update atom cross move

---

dock/cccp/cccp.py
dock/netopter/node_classification.py
island/service/service.py
test/dock/router/test_router.py

Fix unlock bugs

---

dock/cccp/cccp.py
dock/dock.py
dock/netopter/graph_data.py
dock/netopter/network_optimizer.py
dock/netopter/node_classification.py
interface/dci/dci_pb2.py
interface/dci/dci_pb2_grpc.py
island/service/interface/dci/dci_pb2.py
island/service/interface/dci/dci_pb2_grpc.py
island/service/service.py
lane/service/interface/dci/dci_pb2.py
lane/service/interface/dci/dci_pb2_grpc.py
lane/service/service.py
protos/dci/dci.proto
test/dock/netopter/test_node_classification.py

Update shard join
